repos:
  - repo: https://github.com/ikamensh/flynt/
    rev: 1.0.1
    hooks:
      - id: flynt

  - repo: https://github.com/timothycrosley/isort
    rev: 5.11.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.10.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

