[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target-version = ['py37', 'py38', 'py39', 'py310', 'py311', 'py312']


#[tool.isort]
#profile = "black"
#combine_as_imports = true
#skip =  ["venv", "benchmarks"]
